---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Sehen Sie sich die Konfigurationsoptionen der Astra Trident Konfigurationen an. 
---
= Optionen für die Storage-Konfiguration
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sehen Sie sich die Konfigurationsoptionen der Astra Trident Konfigurationen an.



== Globale Konfigurationsoptionen

Diese Konfigurationsoptionen sind für alle Astra Trident Konfigurationen anwendbar, unabhängig von der genutzten Storage-Plattform.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `version`  a| 
Versionsnummer der Konfigurationsdatei
 a| 
`1`



| `storageDriverName`  a| 
Name des Speichertreibers
 a| 
`ontap-nas`, `ontap-san`, `ontap-nas-economy`,
`ontap-nas-flexgroup`, `solidfire-san`



| `storagePrefix`  a| 
Optionales Präfix für Volume-Namen Standard: `netappdvp_`.
 a| 
`staging_`



| `limitVolumeSize`  a| 
Optionale Einschränkung von Volume-Größen. Standard: „“ (nicht erzwungen)
 a| 
`10g`

|===

TIP: Verwenden Sie es nicht `storagePrefix` (Einschließlich Standard) für Element-Back-Ends. Standardmäßig wird der verwendet `solidfire-san` Der Treiber ignoriert diese Einstellung und verwendet kein Präfix. Wir empfehlen die Verwendung einer bestimmten TenantID für die Docker Volume-Zuordnung oder die Verwendung der Attributdaten, die mit der Docker-Version, den Treiber-Informationen und dem Raw-Namen aus Docker gefüllt sind, in Fällen, in denen Namensnennung verwendet wurde.

Es stehen Standardoptionen zur Verfügung, damit Sie sie nicht für jedes erstellte Volume angeben müssen. Der `size` Die Option ist für alle Controller-Typen verfügbar. Im Abschnitt zur ONTAP-Konfiguration finden Sie ein Beispiel dafür, wie Sie die Standard-Volume-Größe festlegen.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `size`  a| 
Optionale Standardgröße für neue Volumes. Standard: `1G`
 a| 
`10G`

|===


== ONTAP-Konfiguration

Zusätzlich zu den oben genannten globalen Konfigurationswerten stehen bei Verwendung von ONTAP folgende Optionen auf oberster Ebene zur Verfügung.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `managementLIF`  a| 
IP-Adresse des ONTAP Management LIF. Sie können einen vollqualifizierten Domänennamen (FQDN) angeben.
 a| 
`10.0.0.1`



| `dataLIF`  a| 
IP-Adresse des LIF-Protokolls.

*ONTAP NAS drivers*: Wir empfehlen die Angabe `dataLIF`. Falls nicht vorgesehen, ruft Astra Trident Daten-LIFs von der SVM ab. Sie können einen vollständig qualifizierten Domänennamen (FQDN) angeben, der für die NFS-Mount-Vorgänge verwendet werden soll. Damit können Sie ein Round-Robin-DNS zum Load-Balancing über mehrere Daten-LIFs erstellen.

*ONTAP-SAN-Treiber*: Geben Sie nicht für iSCSI an. Astra Trident verwendet link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["ONTAP selektive LUN-Zuordnung"^] Um die iSCI LIFs zu ermitteln, die für die Einrichtung einer Multi-Path-Sitzung erforderlich sind. Wenn eine Warnung erzeugt wird `dataLIF` Ist explizit definiert.
 a| 
`10.0.0.2`



| `svm`  a| 
Storage Virtual Machine zu verwenden (erforderlich, falls Management LIF eine Cluster-LIF ist)
 a| 
`svm_nfs`



| `username`  a| 
Benutzername zur Verbindung mit dem Speichergerät
 a| 
`vsadmin`



| `password`  a| 
Passwort für die Verbindung mit dem Speichergerät
 a| 
`secret`



| `aggregate`  a| 
Aggregat für die Bereitstellung (optional, wenn eingestellt, muss der SVM zugewiesen werden) Für das `ontap-nas-flexgroup` Treiber, diese Option wird ignoriert. Alle der SVM zugewiesenen Aggregate werden zur Bereitstellung eines FlexGroup Volumes verwendet.
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
Optionale, fail-Provisioning-Funktion, wenn die Nutzung über diesem Prozentsatz liegt
 a| 
`75%`



| `nfsMountOptions`  a| 
Feingranulare Steuerung der NFS-Mount-Optionen; standardmäßig „-o nfsvers=3“. *Nur für die verfügbar `ontap-nas` Und `ontap-nas-economy` Fahrer*. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Siehe Informationen zur NFS-Host-Konfiguration hier"^].
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Die vom Plug-in verwendete Initiatorgruppe wird standardmäßig verwendet `netappdvp`. *Nur erhältlich für den `ontap-san`dFluss*.
 a| 
`myigroup`



| `limitVolumeSize`  a| 
Maximale anforderbare Volume-Größe und übergeordnete qtree Volume-Größe * Für die `ontap-nas-economy` Treiber, diese Option schränkt zusätzlich die Größe der FlexVols ein, die es erstellt*.
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
Maximale Anzahl der qtrees pro FlexVol, die im Bereich [50, 300] liegen müssen, die Standardeinstellung ist 200. * Für die `ontap-nas-economy` Treiber: Mit dieser Option kann die maximale Anzahl von qtrees pro FlexVol* angepasst werden.
 a| 
`300`

|===
Es stehen Standardoptionen zur Verfügung, um zu vermeiden, dass sie auf jedem von Ihnen erstellten Volume angegeben werden müssen:

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `spaceReserve`  a| 
Modus für Speicherplatzreservierung; `none` (Thin Provisioning) oder `volume` (Dick)
 a| 
`none`



| `snapshotPolicy`  a| 
Zu verwendende Snapshot-Richtlinie, Standard ist `none`
 a| 
`none`



| `snapshotReserve`  a| 
Der Prozentsatz der Snapshot-Reserve ist standardmäßig „“, um den ONTAP-Standardwert zu akzeptieren
 a| 
`10`



| `splitOnClone`  a| 
Teilen Sie einen Klon bei der Erstellung von seinem übergeordneten Element auf. Dies ist standardmäßig der Standardwert `false`
 a| 
`false`



| `encryption`  a| 
Aktiviert NetApp Volume Encryption (NVE) auf dem neuen Volume, standardmäßig aktiviert `false`. NVE muss im Cluster lizenziert und aktiviert sein, damit diese Option verwendet werden kann.

Wenn NAE auf dem Backend aktiviert ist, wird jedes im Astra Trident bereitgestellte Volume NAE aktiviert.

Weitere Informationen finden Sie unter: link:../trident-reco/security-reco.html["Astra Trident arbeitet mit NVE und NAE zusammen"].
 a| 
Richtig



| `unixPermissions`  a| 
NAS-Option für bereitgestellte NFS-Volumes, standardmäßig auf `777`
 a| 
`777`



| `snapshotDir`  a| 
NAS-Option für den Zugriff auf die `.snapshot` Verzeichnis, Standardeinstellung `false`
 a| 
`true`



| `exportPolicy`  a| 
NAS-Option für die zu verwendende NFS-Exportrichtlinie, standardmäßig auf `default`
 a| 
`default`



| `securityStyle`  a| 
NAS-Option für Zugriff auf das bereitgestellte NFS-Volume.

NFS unterstützt `mixed` Und `unix` Sicherheitsstile. Die Standardeinstellung lautet `unix`.
 a| 
`unix`



| `fileSystemType`  a| 
SAN-Option zum Auswählen des Dateisystemtyps, standardmäßig auf `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
Zu verwendende Tiering-Richtlinie, Standard ist `none`; `snapshot-only` Für Konfiguration vor ONTAP 9.5 SVM-DR
 a| 
`none`

|===


=== Skalierungsoptionen

Der `ontap-nas` Und `ontap-san` Treiber erstellen für jedes Docker Volume eine ONTAP FlexVol. ONTAP unterstützt bis zu 1000 FlexVols pro Cluster Node mit einem Cluster maximal 12,000 FlexVols. Wenn die Anforderungen für das Docker Volume diesen Anforderungen entsprechen, wird der angezeigt `ontap-nas` Aufgrund der zusätzlichen Funktionen von FlexVols, wie dem granularen Docker-Volume-Snapshot und Klonen, ist der Treiber die bevorzugte NAS-Lösung.

Wenn Sie mehr Docker Volumes benötigen, als durch die FlexVol-Limits unterstützt werden können, wählen Sie die Option `ontap-nas-economy` Oder im `ontap-san-economy` Treiber.

Der `ontap-nas-economy` Der Treiber erstellt Docker Volumes als ONTAP qtrees innerhalb eines Pools automatisch verwalteter FlexVols. Qtrees bieten eine wesentlich größere Skalierung – bis zu 100,000 pro Cluster-Node und 2,400,000 pro Cluster – zu Lasten einiger Funktionen. Der `ontap-nas-economy` Der Treiber unterstützt keine granularen Snapshots oder Klone von Docker Volumes.


NOTE: Der `ontap-nas-economy` Treiber wird derzeit in Docker Swarm nicht unterstützt, da Swarm die Volume-Erstellung nicht über mehrere Nodes hinweg orchestriert.

Der `ontap-san-economy` Der Treiber erstellt Docker Volumes als ONTAP LUNs in einem gemeinsamen Pool automatisch verwalteter FlexVols. Somit ist jede FlexVol nicht auf nur eine LUN beschränkt und bietet eine bessere Skalierbarkeit für SAN-Workloads. Je nach Storage Array unterstützt ONTAP bis zu 16384 LUNs pro Cluster. Da es sich bei den Volumes um LUNs handelt, unterstützt dieser Treiber granulare Docker Snapshots und Klone.

Wählen Sie die aus `ontap-nas-flexgroup` Treiber zur Erhöhung der Parallelität zu einem einzelnen Volume, das mit Milliarden von Dateien im Petabyte-Bereich wachsen kann. Zu den idealen Anwendungsfällen für FlexGroups gehören KI/ML/DL, Big Data und Analysen, Softwareentwicklung, Streaming, Datei-Repositorys und so weiter. Trident verwendet alle Aggregate, die einer SVM bei der Bereitstellung eines FlexGroup-Volumes zugewiesen sind. Die Unterstützung von FlexGroup in Trident muss darüber hinaus Folgendes beachtet werden:

* ONTAP Version 9.2 oder höher erforderlich.
* Ab diesem Text unterstützt FlexGroups nur NFS v3.
* Empfohlen, die 64-Bit-NFSv3-IDs für die SVM zu aktivieren.
* Die empfohlene minimale FlexGroup-Größe beträgt 100 GB.
* Klonen wird für FlexGroup Volumes nicht unterstützt.


Informationen zu FlexGroups und Workloads, die für FlexGroups geeignet sind, finden Sie im https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["NetApp FlexGroup Volume Best Practices und Implementierungsleitfaden"^].

Um erweiterte Funktionen und die enorme Skalierbarkeit in derselben Umgebung zu erhalten, können Sie mehrere Instanzen des Docker Volume Plug-ins ausführen. Dabei kommt ein Storage-Plug-in zum Einsatz `ontap-nas` Und ein anderes mit `ontap-nas-economy`.



=== Beispiel für ONTAP-Konfigurationsdateien

*NFS Beispiel für `ontap-nas` Fahrer*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
*NFS Beispiel für `ontap-nas-flexgroup` Fahrer*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
*NFS Beispiel für `ontap-nas-economy` Fahrer*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
----
*ISCSI-Beispiel für `ontap-san` Fahrer*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "myigroup"
}
----
*NFS Beispiel für `ontap-san-economy` Fahrer*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "myigroup"
}
----


== Konfiguration von Element Software

Zusätzlich zu den Werten einer globalen Konfiguration sind bei Verwendung von Element Software (NetApp HCI/SolidFire) diese Optionen verfügbar.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `Endpoint`  a| 
\https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
ISCSI-IP-Adresse und -Port
 a| 
10.0.0.7:3260 Uhr



| `TenantName`  a| 
SolidFireF Mandanten zu verwenden (erstellt, falls nicht gefunden)
 a| 
`docker`



| `InitiatorIFace`  a| 
Geben Sie die Schnittstelle an, wenn der iSCSI-Datenverkehr auf eine nicht-Standardschnittstelle beschränkt wird
 a| 
`default`



| `Types`  a| 
QoS-Spezifikationen
 a| 
Siehe das Beispiel unten



| `LegacyNamePrefix`  a| 
Präfix für aktualisierte Trident Installationen. Wenn Sie eine Version von Trident vor 1.3.2 verwendet haben und ein Upgrade mit vorhandenen Volumes durchführen, müssen Sie diesen Wert festlegen, um auf Ihre alten Volumes zuzugreifen, die über die Volume-Name-Methode zugeordnet wurden.
 a| 
`netappdvp-`

|===
Der `solidfire-san` Der Treiber unterstützt Docker Swarm nicht.



=== Beispiel für eine Konfigurationsdatei für die Element Software

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----