---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, astra trident, trident for docker, docker, docker volume 
summary: 'Zum Erstellen von Volumes verwenden Sie den Standard `docker volume` Befehle mit dem bei Bedarf angegebenen Astra Trident-Treibernamen.' 
---
= Arbeiten mit Volumes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Volumes lassen sich ganz einfach mit dem Standard erstellen, klonen und entfernen `docker volume` Befehle mit dem bei Bedarf angegebenen Astra Trident-Treibernamen.



== Erstellen eines Volumes

* Erstellen Sie ein Volume mit einem Treiber unter Verwendung des Standardnamens:
+
[listing]
----
docker volume create -d netapp --name firstVolume
----
* Erstellung eines Volumes mit einer bestimmten Astra Trident Instanz:
+
[listing]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: Falls Sie keine angeben link:volume-driver-options.html["Optionen"^], Die Standardeinstellungen für den Treiber werden verwendet.

* Überschreiben Sie die Standard-Volume-Größe. Beachten Sie das folgende Beispiel, um ein 20 gib-Volume mit einem Treiber zu erstellen:
+
[listing]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: Die Volume-Größen werden als Strings angegeben, die einen ganzzahligen Wert mit optionalen Einheiten enthalten (Beispiel: 10G, 20GB, 3tib). Wenn keine Einheiten angegeben werden, lautet der Standardwert G. Einheiten der Größe können entweder als Befugnisse von 2 (B, KiB, MiB, gib, tib) oder als Befugnis von 10 (B, KB, MB, GB, TB) angegeben werden. Auf Kurzschluss und Einheiten werden 2 Kräfte (G = gib, T = tib, …) verwendet.





== Entfernen Sie ein Volume

* Entfernen Sie das Volume wie jedes andere Docker Volume:
+
[listing]
----
docker volume rm firstVolume
----
+

IMPORTANT: Bei Verwendung des `solidfire-san` Treiber, im obigen Beispiel wird das Volume gelöscht und gelöscht.



Führen Sie die nachstehenden Schritte zum Upgrade von Astra Trident für Docker durch.



== Klonen Sie ein Volume

Bei Verwendung des `ontap-nas`, `ontap-san`, `solidfire-san`, und `gcp-cvs storage drivers`Astra Trident kann Volumes klonen. Bei Verwendung des `ontap-nas-flexgroup` Oder `ontap-nas-economy` Treiber, Klonen wird nicht unterstützt. Wenn Sie ein neues Volume von einem vorhandenen Volume erstellen, wird ein neuer Snapshot erstellt.

* Überprüfen Sie das Volume, um die Snapshots aufzuzählen:
+
[listing]
----
docker volume inspect <volume_name>
----
* Erstellen Sie ein neues Volume von einem vorhandenen Volume aus. Dadurch wird ein neuer Snapshot erstellt:
+
[listing]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* Erstellen Sie ein neues Volume anhand eines vorhandenen Snapshots auf einem Volume. Dadurch wird kein neuer Snapshot erstellt:
+
[listing]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== Beispiel

[listing]
----
docker volume inspect firstVolume

[
    {
        "Driver": "ontap-nas",
        "Labels": null,
        "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
        "Name": "firstVolume",
        "Options": {},
        "Scope": "global",
        "Status": {
            "Snapshots": [
                {
                    "Created": "2017-02-10T19:05:00Z",
                    "Name": "hourly.2017-02-10_1505"
                }
            ]
        }
    }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== Zugriff auf extern erstellte Volumes

Mit Trident können Sie auf extern erstellte Blockgeräte (oder deren Klone) von Containern zugreifen, die Trident verwenden *nur*, wenn sie keine Partitionen haben und ihr Dateisystem von Astra Trident unterstützt wird (z.B. an `ext4`-Formatiert `/dev/sdc1` Nicht über Astra Trident zugänglich).
