---
settings:
  name: Astra Trident
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: trident-rn.html
  versions:
  - name: Astra Trident
    url: "/trident"
    version-number: '23.07'
  - name: Astra Trident
    url: "/trident-2304"
    version-number: '23.04'
  - name: Astra Trident
    url: "/trident-2301"
    version-number: '23.01'
  - name: Astra Trident
    url: "/trident-2210"
    version-number: '22.10'
  - name: Astra Trident
    url: "/trident-2207"
    version-number: '22.07'
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Astra Trident Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/trident-rn.html"
    - title: Frühere Versionen
      url: "/earlier-versions.html"
  - section: trident-get-started
  - section: trident-install
  - section: trident-use
  - section: trident-managing-k8s
  - section: trident-docker
  - section: trident-reco
  - title: Wissen und Support
    entries:
    - title: FAQs
      url: "/faq.html"
    - title: Fehlerbehebung
      url: "/troubleshooting.html"
    - title: Holen Sie sich Hilfe
      url: "/get-help.html"
  - section: trident-reference
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: Die komplette Astra Dokumentation
