---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx 
summary: Erfahren Sie mehr über die Konfiguration eines ONTAP-Backend mit ONTAP-NAS-Treibern. 
---
= Konfigurieren Sie ein ONTAP-NAS-Back-End
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Erfahren Sie mehr über die Konfiguration eines ONTAP-Backend mit ONTAP- und Cloud Volumes ONTAP-NAS-Treibern.

* link:ontap-nas-prep.html["Vorbereitung"]
* link:ontap-nas-examples.html["Konfiguration und Beispiele"]



WARNING: Kunden müssen die verwenden `ontap-nas` Treiber für Produktions-Workloads, die Datensicherung, Disaster Recovery und Mobilität benötigen Astra Control bietet nahtlosen Schutz, Disaster Recovery und Mobilität für Volumes, die mit der erstellt werden `ontap-nas` Treiber. Der `ontap-nas-economy` Der Treiber sollte nur in begrenzten Anwendungsfällen verwendet werden, in denen die zu erwartende Volume-Auslastung wahrscheinlich weit über den von ONTAP unterstützten Systemen liegt und keine erwarteten Anforderungen an Datensicherung, Disaster Recovery oder Mobilität (Verschieben von Volumes zwischen den Kubernetes Clustern) bestehen.



== Benutzerberechtigungen

Astra Trident erwartet, dass er entweder als ONTAP- oder SVM-Administrator ausgeführt wird, in der Regel mit dem `admin` Cluster-Benutzer oder ein `vsadmin` SVM-Benutzer oder ein Benutzer mit einem anderen Namen und derselben Rolle. Astra Trident erwartet, dass bei Amazon FSX für Implementierungen von NetApp ONTAP, über das Cluster entweder als ONTAP- oder SVM-Administrator ausgeführt wird `fsxadmin` Benutzer oder A `vsadmin` SVM-Benutzer oder ein Benutzer mit einem anderen Namen und derselben Rolle. Der `fsxadmin` Der Benutzer ist ein eingeschränkter Ersatz für den Cluster-Admin-Benutzer.


NOTE: Wenn Sie den verwenden `limitAggregateUsage` Parameter, Berechtigungen für Cluster-Admin sind erforderlich. Bei der Verwendung von Amazon FSX für NetApp ONTAP mit Astra Trident, das `limitAggregateUsage` Der Parameter funktioniert nicht mit dem `vsadmin` Und `fsxadmin` Benutzerkonten. Der Konfigurationsvorgang schlägt fehl, wenn Sie diesen Parameter angeben.

Obwohl es möglich ist, eine restriktivere Rolle innerhalb ONTAP, dass ein Trident-Treiber verwenden kann, wir nicht empfehlen es. Bei den meisten neuen Versionen von Trident sind zusätzliche APIs erforderlich, die berücksichtigt werden müssten, was Upgrades schwierig und fehleranfällig macht.
