---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows 
summary: 'Der Trident-Operator ermöglicht es Ihnen, die Art und Weise, wie Astra Trident installiert wird, mithilfe der Attribute im anzupassen `TridentOrchestrator` Spez.' 
---
= Anpassen der Trident Operator-Installation
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Über den Trident-Operator können Sie die Astra Trident-Installation anhand der Attribute im anpassen `TridentOrchestrator` Spez. Wenn Sie die Installation über die von Ihnen gewünschte hinaus anpassen möchten `TridentOrchestrator` Argumente erlauben, verwenden Sie `tridentctl` Um benutzerdefinierte YAML-Manifeste zu erzeugen, die bei Bedarf geändert werden sollen.



== Allgemeines zu Controller-Pods und Node-Pods

Astra Trident wird als einzelner Controller-Pod ausgeführt sowie als Node-Pod auf jedem Worker-Node im Cluster. Der Node Pod muss auf jedem Host ausgeführt werden, auf dem Sie ein Astra Trident Volume mounten möchten.

Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Knotenauswahl"^] Und link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["Toleranzen und Verfleckungen"^] Werden verwendet, um die Ausführung eines Pod auf einem bestimmten oder bevorzugten Node einzuschränken. Verwenden von`ControllerPlugin` und `NodePlugin`, Sie können Bedingungen und Überschreibungen festlegen.

* Das Controller-Plug-in übernimmt Volume-Bereitstellung und -Management, beispielsweise Snapshots und Größenanpassungen.
* Das Node-Plug-in verarbeitet das Verbinden des Speichers mit dem Node.




== Konfigurationsoptionen


WARNING: `spec.namespace` Ist in angegeben `TridentOrchestrator` Um den Namespace zu kennzeichnen, in dem Astra Trident installiert ist. Dieser Parameter *kann nicht aktualisiert werden, nachdem Astra Trident installiert wurde*. Der Versuch, dies zu tun, bewirkt das `TridentOrchestrator` Status zu ändern in `Failed`. Astra Trident ist nicht für die Migration auf Namespaces vorgesehen.

Diese Tabelle enthält Einzelheiten `TridentOrchestrator` Attribute.

[cols="3"]
|===
| Parameter | Beschreibung | Standard 


| `autosupportImage` | Das Container-Image für AutoSupport Telemetrie | „netapp/Trident-AutoSupport:23.07“ 


| `autosupportProxy` | Die Adresse/der Port eines Proxys zum Senden von AutoSupport Telemetrie | "http://proxy.example.com:8888"[] 


| `controllerPluginNodeSelector` | Zusätzliche Node-Selektoren für Pods mit dem Trident Controller CSI Plugin Entspricht dem Format `pod.spec.nodeSelector`. | Kein Standard; optional 


| `controllerPluginTolerations` | Überschreibungen von Verträgungen für Pods mit dem Trident Controller CSI-Plug-in Entspricht dem gleichen Format wie `pod.spec.Tolerations`. | Kein Standard; optional 


| `debug` | Aktivieren Sie das Debugging für Astra Trident | `false` 


| `enableForceDetach` | `ontap-san` Und `ontap-san-economy` Nur. Arbeitet mit Kubernetes Non-Graceful Node Shutdown (NGNS), um Clusteradministratoren die Möglichkeit zu geben, Workloads mit gemounteten Volumes sicher auf neue Nodes zu migrieren, sollte ein Node fehlerhaft werden. *Dies ist ein experimentelles Feature in 23.04.* Siehe <<Details zum Ablösen von Krafteinwirkung>> Wichtige Hinweise. | `false` 


| `imagePullPolicy` | Legt die BildPull-Richtlinie für den Trident-Operator fest. Gültige Werte sind:
`Always` Um immer das Bild zu ziehen.
`IfNotPresent` Nur wenn das Image nicht auf dem Node vorhanden ist, soll das Image kopiert werden.
`Never` Nie das Bild ziehen. | `IfNotPresent` 


| `controllerPluginNodeSelector` | Zusätzliche Node-Auswahl für Pods Entspricht dem gleichen Format wie pod.spec.nodeSelector. | Kein Standard; optional 


| `controllerPluginTolerations` | Überschreibt Kubernetes-Toleranzen für Pods. Entspricht dem gleichen Format wie pod.spec.tolerations. | Kein Standard; optional 


| `nodePluginNodeSelector` | Zusätzliche Node-Auswahl für Pods Entspricht dem gleichen Format wie pod.spec.nodeSelector. | Kein Standard; optional 


| `nodePluginTolerations` | Überschreibt Kubernetes-Toleranzen für Pods. Entspricht dem gleichen Format wie pod.spec.tolerations. | Kein Standard; optional 
|===

NOTE: Weitere Informationen zum Formatieren von Pod-Parametern finden Sie unter link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Pods werden Nodes zugewiesen"^].



=== Details zum Ablösen von Krafteinwirkung

Trennung erzwingen ist für verfügbar `ontap-san` Und `ontap-san-economy` Nur. Vor der Aktivierung von Force Trennen muss das nicht-anmutige Herunterfahren des Node (NGNS) auf dem Kubernetes-Cluster aktiviert sein. Weitere Informationen finden Sie unter link:https://kubernetes.io/docs/concepts/architecture/nodes/#non-graceful-node-shutdown["Kubernetes: Nicht ordnungsgemäßes Herunterfahren von Nodes"^].


WARNING: Da Astra Trident auf Kubernetes NGNS basiert, entfernen Sie nicht `out-of-service` Bleibt bei einem Node in einem unzulässigen Zustand, bis alle nicht tolerierbaren Workloads neu geplant werden. Das rücksichtslose Anwenden oder Entfernen der Schein kann den Schutz der Back-End-Daten gefährden.

Wenn der Kubernetes-Cluster-Administrator den angewendet hat `node.kubernetes.io/out-of-service=nodeshutdown:NoExecute` Taint to the Node and `enableForceDetach` Ist auf festgelegt `true`Astra Trident bestimmt den Node-Status und:

. Beenden Sie den Back-End-I/O-Zugriff für Volumes, die auf diesem Node gemountet sind.
. Markieren Sie das Astra Trident Node-Objekt als `dirty` (Nicht sicher für neue Publikationen).
+

NOTE: Der Trident-Controller lehnt neue Anfragen zu veröffentlichten Volumes ab, bis der Node neu qualifiziert wird (nachdem er als markiert wurde) `dirty`) Durch den Trident Node POD. Alle Workloads, die mit einer gemounteten PVC geplant sind (selbst nachdem der Cluster-Node funktionsfähig und bereit ist), werden erst akzeptiert, wenn Astra Trident den Node überprüfen kann `clean` (Sicher für neue Publikationen).



Wenn der Zustand der Nodes wiederhergestellt und die Wartung entfernt wird, übernimmt Astra Trident folgende Aufgaben:

. Veraltete veröffentlichte Pfade auf dem Node identifizieren und bereinigen.
. Wenn sich der Node in einem befindet `cleanable` Status (die Servicestaint wurde entfernt, und der Node befindet sich in `Ready` Status) und alle veralteten, veröffentlichten Pfade sind sauber. Astra Trident übermittelt den Node als neu `clean` Und neue veröffentlichte Volumes auf dem Knoten zulassen.




== Beispielkonfigurationen

Sie können die oben genannten Attribute beim Definieren verwenden `TridentOrchestrator` Um die Installation anzupassen.

.Beispiel 1: Grundlegende benutzerdefinierte Konfiguration
[%collapsible%open]
====
Dies ist ein Beispiel für eine benutzerdefinierte Grundkonfiguration.

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
====
.Beispiel 2: Implementierung mit Node-Auswahl
[%collapsible%open]
====
Dieses Beispiel veranschaulicht die Implementierung von Trident mit Node-Selektoren:

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====
.Beispiel 3: Bereitstellung auf Windows Worker-Nodes
[%collapsible%open]
====
Dieses Beispiel zeigt die Bereitstellung auf einem Windows Worker-Knoten.

[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----
====