---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: Vor der Installation von Astra Trident sollten Sie diese allgemeinen Systemanforderungen überprüfen. Spezifische Back-Ends können zusätzliche Anforderungen haben. 
---
= Anforderungen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Installation von Astra Trident sollten Sie diese allgemeinen Systemanforderungen überprüfen. Spezifische Back-Ends können zusätzliche Anforderungen haben.



== Entscheidende Informationen zu Astra Trident 23.01

*Sie müssen die folgenden wichtigen Informationen über Astra Trident lesen.*

.<strong> Informationen über Astra TripereIT </strong>
[%collapsible%open]
====
* Kubernetes 1.26 wird jetzt in Trident unterstützt. Upgrade von Trident vor dem Upgrade von Kubernetes.
* Astra Trident setzt die Verwendung von Multipathing-Konfiguration in SAN-Umgebungen strikt um und empfiehlt den Nutzen von `find_multipaths: no` In Multipath.conf Datei.
+
Verwendung einer Konfiguration ohne Multipathing oder Verwendung von `find_multipaths: yes` Oder `find_multipaths: smart` Der Wert in der Multipath.conf-Datei führt zu Mount-Fehlern. Trident empfiehlt die Verwendung von `find_multipaths: no` Seit der Version 21.07.



====


== Unterstützte Frontends (Orchestrators)

Astra Trident unterstützt mehrere Container-Engines und Orchestrierungslösungen. Dazu gehören:

* Anthos On-Prem (VMware) und Anthos auf Bare Metal 1.9, 1.10 und 1.11
* Kubernetes 1.21 - 1.26
* Mirantis Kubernetes Engine 3.5
* OpenShift 4.9 - 4.12


Der Trident-Operator wird durch folgende Versionen unterstützt:

* Anthos On-Prem (VMware) und Anthos auf Bare Metal 1.9, 1.10 und 1.11
* Kubernetes 1.21 - 1.26
* OpenShift 4.9 - 4.12


Astra Trident ist auch mit einer Vielzahl weiterer vollständig gemanagter und selbst verwalteter Kubernetes-Angebote kompatibel, darunter Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Rancher und VMware Tanzu Portfolio.


WARNING: Bevor Sie ein Kubernetes Cluster von 1.24 auf 1.25 oder höher aktualisieren, auf die Astra Trident installiert ist, finden Sie unter link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-based-operator-installation["Aktualisieren einer Helm-basierten Bedienerinstallation"].



== Unterstützte Back-Ends (Storage)

Zur Verwendung von Astra Trident benötigen Sie ein oder mehrere der folgenden unterstützten Back-Ends:

* Amazon FSX für NetApp ONTAP
* Azure NetApp Dateien
* Cloud Volumes ONTAP
* Cloud Volumes Service für GCP
* FAS/All Flash FAS/Select 9.5 oder höher
* NetApp All-SAN-Array (ASA)
* NetApp HCI/Element Software 11 oder höher




== Anforderungen an die Funktionen

Die nachfolgende Tabelle enthält einen Überblick über die Funktionen dieser Version von Astra Trident und die von ihm unterstützten Versionen von Kubernetes.

[cols="3"]
|===
| Merkmal | Kubernetes-Version | Funktionstore erforderlich? 


| CSI Trident  a| 
1.21 - 1.26
 a| 
Nein



| Volume Snapshots  a| 
1.21 - 1.26
 a| 
Nein



| PVC aus Volume Snapshots  a| 
1.21 - 1.26
 a| 
Nein



| ISCSI PV-Größe  a| 
1.21 - 1.26
 a| 
Nein



| Bidirektionales ONTAP-CHAP  a| 
1.21 - 1.26
 a| 
Nein



| Dynamische Exportrichtlinien  a| 
1.21 - 1.26
 a| 
Nein



| Trident Operator  a| 
1.21 - 1.26
 a| 
Nein



| CSI-Topologie  a| 
1.21 - 1.26
 a| 
Nein

|===


== Getestete Host-Betriebssysteme

Der Astra Trident unterstützt zwar bestimmte Betriebssysteme offiziell nicht, doch ist es bekannt, dass folgende Betriebssysteme funktionieren:

* Versionen von redhat CoreOS (RHCOS) werden von OpenShift Container Platform unterstützt
* RHEL 8 ODER HÖHER
* Ubuntu 22.04 oder höher
* Windows Server 2019


Standardmäßig wird Astra Trident in einem Container ausgeführt und läuft daher auf jedem Linux-Mitarbeiter. Diese Mitarbeiter müssen jedoch in der Lage sein, die Volumes, die Astra Trident bietet, je nach den von Ihnen verwendeten Back-Ends mit dem standardmäßigen NFS-Client oder iSCSI-Initiator zu mounten.

Der `tridentctl` Utility läuft auch auf jeder dieser Linux-Distributionen.



== Host-Konfiguration

Alle Worker-Nodes im Kubernetes-Cluster müssen in der Lage sein, die Volumes, die Sie für Ihre Pods bereitgestellt haben, zu mounten. Um die Worker-Knoten vorzubereiten, müssen Sie die NFS- oder iSCSI-Tools auf der Grundlage Ihrer Treiberauswahl installieren.

link:../trident-use/worker-node-prep.html["Bereiten Sie den Knoten „Worker“ vor"]



== Konfiguration des Storage-Systems

Astra Trident erfordert möglicherweise Änderungen an einem Storage-System, bevor es mit einer Backend-Konfiguration verwendet werden kann.

link:../trident-use/backends.html["Back-Ends konfigurieren"]



== Astra Trident-Ports

Astra Trident erfordert Zugriff auf spezifische Ports für die Kommunikation.

link:../trident-reference/ports.html["Astra Trident-Ports"]



== Container-Images und entsprechende Kubernetes-Versionen

Bei luftvergaschten Installationen ist die folgende Liste eine Referenz für Container-Images, die für die Installation von Astra Trident erforderlich sind. Verwenden Sie die `tridentctl images` Befehl zum Überprüfen der Liste der erforderlichen Container-Images.

[cols="2"]
|===
| Kubernetes-Version | Container-Image 


| V1.21,0  a| 
* netapp/Trident:23.01.1
* netapp/Trident: 23.01
* K8s.io/sig-Storage/csi-bereitstellung:v3.4.0
* K8s.io/sig-Storage/csi-Attacher:v4.1.0
* K8s.io/sig-Storage/csi-resizer:v1.7.0
* K8s.io/sig-Storage/csi-Snapshots: V6.2.1
* K8s.io/sig-Storage/csi-Node-driver-registrar:v2.7.0
* netapp/Trident-Betreiber: 23.01.1 (optional)




| V1.22.0  a| 
* netapp/Trident:23.01.1
* netapp/Trident: 23.01
* K8s.io/sig-Storage/csi-bereitstellung:v3.4.0
* K8s.io/sig-Storage/csi-Attacher:v4.1.0
* K8s.io/sig-Storage/csi-resizer:v1.7.0
* K8s.io/sig-Storage/csi-Snapshots: V6.2.1
* K8s.io/sig-Storage/csi-Node-driver-registrar:v2.7.0
* netapp/Trident-Betreiber: 23.01.1 (optional)




| V1.23.0  a| 
* netapp/Trident:23.01.1
* netapp/Trident: 23.01
* K8s.io/sig-Storage/csi-bereitstellung:v3.4.0
* K8s.io/sig-Storage/csi-Attacher:v4.1.0
* K8s.io/sig-Storage/csi-resizer:v1.7.0
* K8s.io/sig-Storage/csi-Snapshots: V6.2.1
* K8s.io/sig-Storage/csi-Node-driver-registrar:v2.7.0
* netapp/Trident-Betreiber: 23.01.1 (optional)




| V1.24.0  a| 
* netapp/Trident:23.01.1
* netapp/Trident: 23.01
* K8s.io/sig-Storage/csi-bereitstellung:v3.4.0
* K8s.io/sig-Storage/csi-Attacher:v4.1.0
* K8s.io/sig-Storage/csi-resizer:v1.7.0
* K8s.io/sig-Storage/csi-Snapshots: V6.2.1
* K8s.io/sig-Storage/csi-Node-driver-registrar:v2.7.0
* netapp/Trident-Betreiber: 23.01.1 (optional)




| V1.25.0  a| 
* netapp/Trident:23.01.1
* netapp/Trident: 23.01
* K8s.io/sig-Storage/csi-bereitstellung:v3.4.0
* K8s.io/sig-Storage/csi-Attacher:v4.1.0
* K8s.io/sig-Storage/csi-resizer:v1.7.0
* K8s.io/sig-Storage/csi-Snapshots: V6.2.1
* K8s.io/sig-Storage/csi-Node-driver-registrar:v2.7.0
* netapp/Trident-Betreiber: 23.01.1 (optional)




| V1.26.0  a| 
* netapp/Trident:23.01.1
* netapp/Trident: 23.01
* K8s.io/sig-Storage/csi-bereitstellung:v3.4.0
* K8s.io/sig-Storage/csi-Attacher:v4.1.0
* K8s.io/sig-Storage/csi-resizer:v1.7.0
* K8s.io/sig-Storage/csi-Snapshots: V6.2.1
* K8s.io/sig-Storage/csi-Node-driver-registrar:v2.7.0
* netapp/Trident-Betreiber: 23.01.1 (optional)


|===

NOTE: Verwenden Sie in Kubernetes ab Version 1.21 das validierte `registry.k8s.gcr.io/sig-storage/csi-snapshotter:v6.x` Bild nur, wenn der `v1` Version stellt den bereit `volumesnapshots.snapshot.storage.k8s.gcr.io` CRD.- Wenn der `v1beta1` Die Version dient der CRD mit/ohne dem `v1` Verwenden Sie die validierte Version `registry.k8s.gcr.io/sig-storage/csi-snapshotter:v3.x` Bild:
