---
sidebar: sidebar 
permalink: trident-concepts/ontap-drivers.html 
keywords: trident backend, AFF, FAS, ONTAP Select, Cloud, Amazon FSx for NetApp ONTAP, drivers, ONTAP drivers 
summary: Erfahren Sie, wie Sie mit Ihrer Trident Installation ein Element Backend erstellen und verwenden. 
---
= ONTAP-Treiber
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident bietet fünf einzigartige ONTAP-Storage-Treiber für die Kommunikation mit ONTAP Clustern. Erfahren Sie mehr darüber, wie jeder Treiber die Erstellung von Volumes und Zugriffssteuerung sowie seine Funktionen übernimmt.



== Erfahren Sie mehr über die ONTAP Storage-Treiber

[WARNING]
====
Astra Control bietet nahtlosen Schutz, Disaster Recovery und Mobilität (Verschieben von Volumes zwischen Kubernetes Clustern) für Volumes, die mit der erstellt wurden `ontap-nas`, `ontap-nas-flexgroup`, und `ontap-san` Treiber. Siehe link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Voraussetzungen für die Astra Control Replikation"^] Entsprechende Details.

* Sie müssen verwenden `ontap-nas` Für produktive Workloads, die Datensicherung, Disaster Recovery und Mobilität erfordern.
* Nutzung `ontap-san-economy` Nach einer voraussichtlichen Volume-Nutzung ist zu erwarten, dass sie wesentlich höher ist, als das von ONTAP unterstützt wird.
* Nutzung `ontap-nas-economy` Nur in dem eine zu erwartende Volume-Nutzung größer als die von ONTAP wird, und `ontap-san-economy` Treiber kann nicht verwendet werden.
* Verwenden Sie ihn nicht `ontap-nas-economy` Wenn Sie die Notwendigkeit von Datensicherung, Disaster Recovery oder Mobilität erwarten.


====
[cols="5"]
|===
| Treiber | Protokoll | VolumeModus | Unterstützte Zugriffsmodi | Unterstützte Filesysteme 


| `ontap-nas`  a| 
NFS
 a| 
Dateisystem
 a| 
RWO, ROX, RWX
 a| 
„“, nfs



| `ontap-nas-economy`  a| 
NFS
 a| 
Dateisystem
 a| 
RWO, ROX, RWX
 a| 
„“, nfs



| `ontap-nas-flexgroup`  a| 
NFS
 a| 
Dateisystem
 a| 
RWO, ROX, RWX
 a| 
„“, nfs



| `ontap-san`  a| 
ISCSI
 a| 
Block-Storage
 a| 
RWO, ROX, RWX
 a| 
Kein Filesystem, rohes Block-Gerät



| `ontap-san`  a| 
ISCSI
 a| 
Dateisystem
 a| 
RWO, ROX

RWX ist im Volume-Modus des Dateisystems nicht verfügbar.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san-economy`  a| 
ISCSI
 a| 
Block-Storage
 a| 
RWO, ROX, RWX
 a| 
Kein Filesystem, rohes Block-Gerät



| `ontap-san-economy`  a| 
ISCSI
 a| 
Dateisystem
 a| 
RWO, ROX

RWX ist im Volume-Modus des Dateisystems nicht verfügbar.
 a| 
`xfs`, `ext3`, `ext4`

|===

NOTE: ONTAP-Back-Ends können mit Anmeldeinformationen für eine Sicherheitsrolle (Benutzername/Passwort) oder mit dem privaten Schlüssel und dem Zertifikat, das auf dem ONTAP-Cluster installiert ist, authentifiziert werden. Sie können vorhandene Back-Ends aktualisieren, um mit von einem Authentifizierungsmodus in den anderen zu verschieben `tridentctl update backend`.
