---
sidebar: sidebar 
permalink: trident-reference/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Erfahren Sie mehr über tridentctl, ein Befehlszeilenprogramm mit einfachem Zugriff auf Trident. 
---
= Tridentctl-Befehle und -Optionen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der https://github.com/NetApp/trident/releases["Trident Installationspaket"^] Enthält ein Befehlszeilendienstprogramm, `tridentctl`, Das ist ein einfacher Zugriff auf Astra Trident. Kubernetes-Benutzer mit ausreichenden Berechtigungen können es verwenden, um Astra Trident zu installieren und direkt damit zu interagieren, um den Namespace zu managen, der den Astra Trident Pod enthält.



== Verfügbare Befehle und Optionen

Führen Sie zur Verwendung Informationen aus `tridentctl --help`.

Die verfügbaren Befehle und globalen Optionen sind:

[listing]
----
Usage:
  tridentctl [command]
----
Verfügbare Befehle:

* `create`: Fügen Sie eine Ressource zu Astra Trident hinzu.
* `delete`: Entfernen Sie eine oder mehrere Ressourcen von Astra Trident.
* `get`: Holen Sie sich eines oder mehrere Ressourcen von Astra Trident.
* `help`: Hilfe zu jedem Befehl.
* `images`: Drucken Sie eine Tabelle der Container-Bilder, die Astra Trident braucht.
* `import`: Import einer vorhandenen Ressource zu Astra Trident.
* `install`: Installation Astra Trident:
* `logs`: Drucken Sie die Protokolle von Astra Trident.
* `send`: Senden Sie eine Ressource von Astra Trident.
* `uninstall`: Astra Trident Deinstallieren.
* `update`: Ändern Sie eine Ressource in Astra Trident.
* `upgrade`: Upgrade einer Ressource in Astra Trident.
* `version`: Drucken Sie die Version von Astra Trident.


Markierungen:

* ``-d, --debug`: Debug-Ausgabe.
* ``-h, --help`: Hilfe für `tridentctl`.
* ``-n, --namespace string`: Namespace für Astra Trident Implementierung.
* ``-o, --output string`: Ausgabeformat. Einer von json yaml-Namen natürlich Ärmellos (Standard).
* ``-s, --server string`: Adresse/Port des Astra Trident REST Interface.
+

CAUTION: Die Trident REST-Schnittstelle kann nur für die Wiedergabe unter 127.0.0.1 (für IPv4) oder [: 1] (für IPv6) konfiguriert werden.




CAUTION: Die Trident REST-Schnittstelle kann nur für die Wiedergabe unter 127.0.0.1 (für IPv4) oder [: 1] (für IPv6) konfiguriert werden.



== `create`

Sie können den ausführen `create` Befehl zum Hinzufügen einer Ressource zum Astra Trident.

[listing]
----
Usage:
  tridentctl create [option]
----
Verfügbare Option:
`backend`: Fügen Sie ein Backend zu Astra Trident hinzu.



== `delete`

Sie können die ausführen `delete` Befehl, um eine oder mehrere Ressourcen aus Astra Trident zu entfernen.

[listing]
----
Usage:
  tridentctl delete [option]
----
Verfügbare Optionen:

* `backend`: Löschen Sie ein oder mehrere Storage-Back-Ends von Astra Trident.
* `snapshot`: Löschen Sie einen oder mehrere Volumen-Snapshots aus Astra Trident.
* `storageclass`: Löschen einer oder mehrerer Speicherklassen von Astra Trident.
* `volume`: Löschen Sie ein oder mehrere Storage Volumes von Astra Trident.




== `get`

Sie können die ausführen `get` Befehl: Sie erhalten eine oder mehrere Ressourcen von Astra Trident.

[listing]
----
Usage:
  tridentctl get [option]
----
Verfügbare Optionen:

* `backend`: Holen Sie sich ein oder mehrere Storage Back-Ends von Astra Trident an.
* `snapshot`: Holen Sie sich einen oder mehrere Schnappschüsse von Astra Trident.
* `storageclass`: Holen Sie sich einen oder mehrere Storage-Kurse von Astra Trident.
* `volume`: Holen Sie sich ein oder mehrere Bände von Astra Trident.


`volume` Flaggen: * ``-h, --help`: Hilfe für Volumen. * `--parentOfSubordinate string`: Abfrage auf untergeordnetes Quellvolumen begrenzen. * `--subordinateOf string`: Abfrage auf Untergebene beschränken.



== `images`

Sie können die ausführen `images` Flagge, um eine Tabelle der Container-Bilder zu drucken, die Astra Trident benötigt.

[listing]
----
Usage:
  tridentctl images [flags]
----
Flaggen: * ``-h, --help`: Help for images.
* ``-V, --k8s-Version string`: Semantische Version des Kubernetes Clusters.



== `import volume`

Sie können die ausführen `import volume` Befehl zum Importieren eines vorhandenen Volumes zu Astra Trident

[listing]
----
Usage:
  tridentctl import volume <backendName> <volumeName> [flags]
----
Aliase:
`volume, v`

Markierungen:

* ``-f, --filename string`: Pfad zu YAML oder JSON PVC-Datei.
* ``-h, --help`: Hilfe für Lautstärke.
* ``--no-manage`: Nur PV/PVC erstellen. Nehmen Sie kein Lifecycle Management für Volumes an.




== `install`

Sie können die ausführen `install` Flags für die Installation von Astra Trident.

[listing]
----
Usage:
  tridentctl install [flags]
----
Markierungen:

* ``--autosupport-image string`: Das Container-Image für AutoSupport Telemetry (Standard „netapp/Trident AutoSupport:20.07.0“).
* ``--autosupport-proxy string`: Die Adresse/der Port eines Proxy für den Versand von AutoSupport Telemetrie.
* ``--csi`: CSI Trident installieren (Überschreiben nur für Kubernetes 1.13, erfordert Feature-Gates).
* ``--enable-node-prep`: Versuch, benötigte Pakete auf Knoten zu installieren.
* ``--generate-custom-yaml`: Erzeugen von YAML-Dateien ohne Installation von irgendetwas.
* ``-h, --help`: Hilfe zur Installation.
* ``--http-request-timeout`: Überschreiben Sie die HTTP-Anforderung-Timeout für die REST-API des Trident-Controllers (Standard 1m30s).
* ``--image-registry string`: Die Adresse/der Port einer internen Bilddatenbank.
* ``--k8s-timeout duration`: Die Zeitüberschreitung für alle Kubernetes-Operationen (Standard 3m0s).
* ``--kubelet-dir string`: Der Host-Standort des internen Status von kubelet (Standard "/var/lib/kubelet").
* ``--log-format string`: Das Astra Trident Logging-Format (Text, json) (Standard "Text").
* ``--pv string`: Der Name des alten PV, das von Astra Trident verwendet wird, stellt sicher, dass dies nicht existiert (Standard "Dreizack").
* ``--pvc string`: Der Name des alten PVC verwendet von Astra Trident, stellt sicher, dass dies nicht existiert (Standard "Dreizack").
* ``--silence-autosupport`: AutoSupport Bundles nicht automatisch an NetApp senden (standardmäßig wahr).
* ``--silent`: Während der Installation die meiste Leistung deaktivieren.
* ``--trident-image string`: Das zu installierende Astra Trident-Image.
* ``--use-custom-yaml`: Verwenden Sie alle bestehenden YAML-Dateien, die im Setup-Verzeichnis vorhanden sind.
* ``--use-ipv6`: Nutzen Sie IPv6 für die Kommunikation von Astra Trident.




== `logs`

Sie können die ausführen `logs` Flags zum Drucken der Protokolle von Astra Trident.

[listing]
----
Usage:
  tridentctl logs [flags]
----
Markierungen:

* ``-a, --archive`: Erstellen Sie ein Stützarchiv mit allen Protokollen, sofern nicht anders angegeben.
* ``-h, --help`: Hilfe für Protokolle.
* ``-l, --log string`: Astra Trident Log to Display. Einer der Dreizack-Automatik-Operator ganz (Standard „Auto“).
* ``--node string`: Der Kubernetes-Knotenname, aus dem Node-Pod-Protokolle erfasst werden.
* ``-p, --previous`: Holen Sie sich die Protokolle für die frühere Container-Instanz, wenn sie existiert.
* ``--sidecars`: Holen Sie sich die Protokolle für die Sidecar-Container.




== `send`

Sie können die ausführen `send` Befehl zum Senden einer Ressource vom Astra Trident.

[listing]
----
Usage:
  tridentctl send [option]
----
Verfügbare Option:
`autosupport`: Senden Sie ein AutoSupport-Archiv an NetApp.



== `uninstall`

Sie können die ausführen `uninstall` Flags zum Deinstallieren von Astra Trident.

[listing]
----
Usage:
  tridentctl uninstall [flags]
----
Flaggen: * `-h, --help`: Hilfe zur Deinstallation. * `--silent`: Deaktivieren der meisten Ausgabe während der Deinstallation.



== `update`

Sie können die ausführen `update` Befehle zum Ändern einer Ressource in Astra Trident.

[listing]
----
Usage:
  tridentctl update [option]
----
Verfügbare Optionen:
`backend`: Aktualisieren Sie ein Backend im Astra Trident.



== `upgrade`

Sie können die ausführen `upgrade` Befehle für das Upgrade einer Ressource in Astra Trident.

[listing]
----
Usage:
tridentctl upgrade [option]
----
Verfügbare Option:
`volume`: Upgrade eines oder mehrerer persistenter Volumes von NFS/iSCSI auf CSI.



== `version`

Sie können die ausführen `version` Flags zum Drucken der Version von `tridentctl` Und den Running Trident Service.

[listing]
----
Usage:
  tridentctl version [flags]
----
Flaggen: * `--client`: Nur Client-Version (kein Server erforderlich). * `-h, --help`: Hilfe zur Version.
