---
sidebar: sidebar 
permalink: trident-reference/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Erfahren Sie mehr über tridentctl, ein Befehlszeilenprogramm mit einfachem Zugriff auf Trident. 
---
= Managen Sie Astra Trident mit tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der https://github.com/NetApp/trident/releases["Trident Installationspaket"^] Umfasst die `tridentctl` Befehlszeilen-Utility für einfachen Zugriff auf Astra Trident. Kubernetes-Benutzer mit ausreichenden Berechtigungen können damit Astra Trident installieren oder den Namespace managen, der den Astra Trident Pod enthält.



== Befehle und globale Alarmmeldungen

Sie können laufen `tridentctl help` Um eine Liste der verfügbaren Befehle für zu erhalten `tridentctl` Oder hängen Sie die an `--help` Markieren Sie einen beliebigen Befehl, um eine Liste mit Optionen und Flags für diesen bestimmten Befehl zu erhalten.

Zu Verwenden::


[listing]
----
tridentctl [command] [--optional-flag]
----
Astra Trident `tridentctl` Utility unterstützt die folgenden Befehle und Global Flags.

.Befehle
[%collapsible]
====
`create`:: Ressource zu Astra Trident hinzufügen.
`delete`:: Entfernen Sie eine oder mehrere Ressourcen aus Astra Trident.
`get`:: Holen Sie sich eine oder mehrere Ressourcen von Astra Trident.
`help`:: Hilfe zu jedem Befehl.
`images`:: Drucken Sie eine Tabelle der Container-Images, die Astra Trident benötigt.
`import`:: Importieren Sie eine vorhandene Ressource in Astra Trident.
`install`:: Installation Von Astra Trident:
`logs`:: Protokolle aus Astra Trident drucken.
`send`:: Senden Sie eine Ressource von Astra Trident.
`uninstall`:: Deinstallieren Sie Astra Trident.
`update`:: Ändern Sie eine Ressource in Astra Trident.
`update backend state`:: Vorübergehende Unterbrechung der Back-End-Vorgänge.
`upgrade`:: Aktualisieren Sie eine Ressource in Astra Trident.
`version`:: Drucken Sie die Version von Astra Trident.


====
.Globale Alarmmeldungen
[%collapsible]
====
`-d`, `--debug`:: Debug-Ausgabe.
`-h`, `--help`:: Hilfe für `tridentctl`.
`-n`, `--namespace string`:: Namespace für die Astra Trident-Implementierung.
`-o`, `--output string`:: Ausgabeformat. Einer von json yaml-Namen natürlich Ärmellos (Standard).
`-s`, `--server string`:: Adresse/Port der Astra Trident REST-Schnittstelle
+
--

WARNING: Die Trident REST-Schnittstelle kann nur für die Wiedergabe unter 127.0.0.1 (für IPv4) oder [: 1] (für IPv6) konfiguriert werden.

--


====


== Befehlsoptionen und -Flags



=== `create`

Verwenden Sie die `create` Befehl zum Hinzufügen einer Ressource zum Astra Trident.

Zu Verwenden::


[listing]
----
tridentctl create [option]
----
Optionen:: Back-End zu Astra Trident hinzufügen




=== `delete`

Verwenden Sie die `delete` Befehl, um eine oder mehrere Ressourcen aus Astra Trident zu entfernen.

Zu Verwenden::


[listing]
----
tridentctl delete [option]
----
Optionen:: Löschen Sie ein oder mehrere Storage-Back-Ends aus Astra Trident.
`snapshot`:: Löschen Sie einen oder mehrere Volume-Snapshots aus Astra Trident.
`storageclass`:: Löschen Sie eine oder mehrere Storage-Klassen aus Astra Trident.
`volume`:: Löschen Sie ein oder mehrere Storage-Volumes aus Astra Trident.




=== `get`

Verwenden Sie die `get` Befehl: Sie erhalten eine oder mehrere Ressourcen von Astra Trident.

Zu Verwenden::


[listing]
----
tridentctl get [option]
----
Optionen:: Erhalten Sie ein oder mehrere Storage-Backends aus Astra Trident.
`snapshot`:: Erhalten Sie einen oder mehrere Snapshots von Astra Trident.
`storageclass`:: Holen Sie sich über Astra Trident eine oder mehrere Storage-Klassen.
`volume`:: Holen Sie sich ein oder mehrere Volumes von Astra Trident.
Flags:: Hilfe für Volumes.
`--parentOfSubordinate string`:: Abfrage auf untergeordnetes Quellvolume beschränken.
`--subordinateOf string`:: Beschränken Sie die Abfrage auf untergeordnete Elemente des Volumes.




=== `images`

Nutzung `images` Flags zum Drucken einer Tabelle der Container-Images, die Astra Trident benötigt.

Zu Verwenden::


[listing]
----
tridentctl images [flags]
----
Flags:: Hilfe für Bilder.
`-v`, `--k8s-version string`:: Semantische Version des Kubernetes Clusters.




=== `import volume`

Verwenden Sie die `import volume` Befehl zum Importieren eines vorhandenen Volumes zu Astra Trident

Zu Verwenden::


[listing]
----
tridentctl import volume <backendName> <volumeName> [flags]
----
Alias:: `volume, v`
Flags:: Pfad zur YAML- oder JSON-PVC-Datei.
`-h`, `--help`:: Hilfe für Volumen.
`--no-manage`:: Nur PV/PVC erstellen. Nehmen Sie kein Lifecycle Management für Volumes an.




=== `install`

Verwenden Sie die `install` Flags für die Installation von Astra Trident.

Zu Verwenden::


[listing]
----
tridentctl install [flags]
----
Flags:: Das Container-Image für AutoSupport Telemetrie (Standardeinstellung „netapp/Trident AutoSupport:<current-version>“).
`--autosupport-proxy string`:: Die Adresse/den Port eines Proxys zum Senden von AutoSupport Telemetrie.
`--enable-node-prep`:: Es wird versucht, erforderliche Pakete auf den Nodes zu installieren.
`--generate-custom-yaml`:: Generieren Sie YAML-Dateien, ohne etwas zu installieren.
`-h`, `--help`:: Hilfe zur Installation.
`--http-request-timeout`:: Überschreiben Sie das HTTP-Anforderungs-Timeout für die REST-API des Trident-Controllers (Standard: 1 m30 s).
`--image-registry string`:: Die Adresse/den Port einer internen Image-Registrierung.
`--k8s-timeout duration`:: Das Zeitlimit für alle Kubernetes-Vorgänge (standardmäßig 3 m0s).
`--kubelet-dir string`:: Der Host-Speicherort des internen Status von kubelet (Standardeinstellung „/var/lib/kubelet“).
`--log-format string`:: Das Astra Trident Protokollierungsformat (Text, json) (standardmäßig „Text“).
`--pv string`:: Der Name des Legacy-PV, der von Astra Trident verwendet wird, stellt sicher, dass es nicht existiert (Standard „Trident“).
`--pvc string`:: Der Name der Legacy-PVC, die von Astra Trident verwendet wird, stellt sicher, dass diese nicht existiert (Standard „Trident“).
`--silence-autosupport`:: Senden Sie AutoSupport Bundles nicht automatisch an NetApp (Standardeinstellung ist „true“).
`--silent`:: Deaktivieren Sie die meisten Ausgaben während der Installation.
`--trident-image string`:: Das zu installierende Astra Trident Image.
`--use-custom-yaml`:: Verwenden Sie alle vorhandenen YAML-Dateien, die im Setup-Verzeichnis vorhanden sind.
`--use-ipv6`:: Verwenden Sie IPv6 zur Kommunikation von Astra Trident.




=== `logs`

Nutzung `logs` Flags zum Drucken der Protokolle von Astra Trident.

Zu Verwenden::


[listing]
----
tridentctl logs [flags]
----
Flags:: Erstellen Sie ein Supportarchiv mit allen Protokollen, sofern nicht anders angegeben.
`-h`, `--help`:: Hilfe für Protokolle.
`-l`, `--log string`:: Astra Trident Protokoll wird angezeigt. Einer der Dreizack-Automatik-Operator ganz (Standard „Auto“).
`--node string`:: Der Kubernetes Node-Name, aus dem Node-Pod-Protokolle erfasst werden sollen.
`-p`, `--previous`:: Rufen Sie die Protokolle für die vorherige Container-Instanz ab, falls sie vorhanden ist.
`--sidecars`:: Holen Sie sich die Protokolle für die Seitenwagen-Container.




=== `send`

Verwenden Sie die `send` Befehl zum Senden einer Ressource vom Astra Trident.

Zu Verwenden::


[listing]
----
tridentctl send [option]
----
Optionen:: Senden Sie ein AutoSupport-Archiv an NetApp.




=== `uninstall`

Nutzung `uninstall` Flags zum Deinstallieren von Astra Trident.

Zu Verwenden::


[listing]
----
tridentctl uninstall [flags]
----
Flags:: Hilfe zur Deinstallation.
`--silent`:: Deaktivieren Sie die meisten Ausgaben während der Deinstallation.




=== `update`

Verwenden Sie die `update` Befehl zum Ändern einer Ressource in Astra Trident.

Zu Verwenden::


[listing]
----
tridentctl update [option]
----
Optionen:: Aktualisieren Sie ein Back-End in Astra Trident.




=== `update backend state`

Verwenden Sie die `update backend state` Befehl zum Anhalten oder Fortsetzen von Back-End-Vorgängen.

Zu Verwenden::


[listing]
----
tridentctl update backend state <backend-name> [flag]
----
Flags:: Auf einstellen `suspended` Um Back-End-Vorgänge anzuhalten. Auf einstellen `normal` Um die Back-End-Vorgänge wieder aufzunehmen. Wenn eingestellt auf `suspended`:
+
--
* `AddVolume`, `CloneVolume`, `Import Volume`, `ResizeVolume` Wurden angehalten.
* `PublishVolume`, `UnPublishVolume`, `CreateSnapshot`, `GetSnapshot`, `RestoreSnapshot`, `DeleteSnapshot`, `RemoveVolume`, `GetVolumeExternal`, `ReconcileNodeAccess` Verfügbar bleiben.


--
`-h`, `--help`:: Hilfe zum Back-End-Status.




=== `version`

Nutzung `version` Flags zum Drucken der Version von `tridentctl` Und den Running Trident Service.

Zu Verwenden::


[listing]
----
tridentctl version [flags]
----
Flags:: Nur Client-Version (kein Server erforderlich).
`-h, --help`:: Hilfe zur Version.

